---
title: "Graphics with ggplot2"
author: "AHF"
date: "2018-10-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ggplot2 - learning (with github)
*and tidyverse*

```{r set up library, echo=FALSE}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("ggthemes")
library(ggthemes)
library(viridis)
```


```{r code for ggplot2, echo=FALSE}
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")

```



Start with the California ('ca') dataset
Plot visualization to all CA BNtional Parks over time
```{r}
ggplot(data = ca) + 
  geom_point(aes(x = year, y = visitors)) #what is the kind of plot = geom

```
next iteration:
color code by park name
```{r}
ggplot(data = ca) + 
  geom_point(aes(x = year, y = visitors, color = park_name)) # within aes , color is a variable mapping to a certain item

```



```{r}
ggplot(data = ca) + 
  geom_point(aes(x = year, y = visitors, color = park_name))+
  labs( x = "Year", y = "Visitors", title = "California National Park Visitors") +
  theme_bw() +#
  theme(legend.title=element_blank())

```
```{r, exercise}
ggplot(data = se) + 
  geom_point(aes(x = year, y = visitors, color = state))+
  labs( x = "Year", y = "Visitors", title = "Southeast National Park Visitors") +
  theme_bw() +#
  theme(legend.title=element_blank())

```
```{r}
ggplot(data = se) + 
  geom_point(aes(x = year, y = visitors, color = state))+
  labs( x = "Year", y = "Visitors", title = "Southeast National Park Visitorsby state") +
  theme_bw() +#
  theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, size = 12, hjust =1))
  
```

# Faceting plots
```{r}
ggplot(data = se) +
  geom_point(aes(x=year,y=visitors, color =park_name))+
  facet_wrap(~state, scales ="free")
theme(axis.text.x = element_text(angle = 90))
```

```{r}
ggplot(data = se)+
  geom_jitter(aes(x=park_name,y=visitors),alpha=0.4, width = 0.1, color = "blue") +
  coord_flip()
```



```{r}
ggplot(se)+
  geom_line(aes(x=year,y=visitors,color=park_name))+
  scale_color_viridis(discrete = TRUE,option = "B")
  theme_bw()
```
```{r several types of plots in one}
ggplot(data=acadia, aes(x=year,y=visitors))+
  geom_point() +
  geom_line() +
  geom_smooth()
```

```{r}
ggplot(data = visit_16, aes(x = state, y =visitors, fill = park_name))+ 
  geom_bar(stat="identity", position = "dodge")


```

#How to save a ggplot
```{r}
 ggplot(data = visit_16, aes(x = state, y =visitors, fill = park_name))+ 
  geom_bar(stat="identity", position = "dodge")+
  scale_fill_viridis(discrete = TRUE)
  
myplot

#ggsave(filename = "myplot.png", myplot)
```